### ISSUE TITLE
text.trim() in Mailbox.js does nothing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [muratgozel/MIMEText#15]
Hi! I was peeking through your source code and noticed this:

https://github.com/muratgozel/MIMEText/blob/25c534b11ed136f2518ae831015517a8b6d0a8c0/src/Mailbox.js#L38

`text.trim()` on its own does nothing. Was this meant to be `text = text.trim()`?

**Comment by muratgozel** [comment]
Hey 👋 sorry for returning late. You have touched a valid point. Could you make a PR for that?
