### ISSUE TITLE
[Question] MIME object from raw email data

### ISSUE THREAD

**Issue by GTP95** [muratgozel/MIMEText#17]
Greetings,

Is it possible to create a MIME message object from an RFC-2822 compliant email message (e.g. the output of the `asRaw()` method)? How?
Thank you for the information,

Giacomo

**Comment by muratgozel** [comment]
Hello 👋 sorry for returning late. Did you have found a solution for parsing rfc-2822 compliant messages? This library only able to generate it, not parse it unfortunately.

**Comment by GTP95** [comment]
Yes, I'm using `emailjs-mime-parser`. Thank you.
