### ISSUE TITLE
allow override envctx when createMimeMessage

### ISSUE THREAD

**Issue by rugbbyli** [muratgozel/MIMEText#19]
The default implementation of envctx using `btoa` function to encode base64 string, which may cause runtime  error in some browser environment, make this library not working at all. There is many third modules can replace this function, so it may be good to have a choice to build custom envctx.

**Comment by muratgozel** [comment]
Yes we can implement a polyfill for the `btoa` function, but I didn't think this module would be used in browsers. I didn't even analyse what other problems could arise in browser environments. Don't you think is it more appropriate to put this lib into the server?

**Comment by rugbbyli** [comment]
Maybe it's more appropriate to using in server, but my needs was to build mimetext under browser environment (it's a react app). There is very limited libs to choose, this is the best one I found. Also, I already tested the lib using some hack method, and it works as expected.

So if you can support that, it could be a good choose for frond end developers.

My temporary solution to replace the builtin btoa function with a third lib's implementation:
```javascript
import { encode } from "js-base64";

const envctx = {
    toBase64: function toBase64(data) {
        return encode(data)
    },
    toBase64WebSafe: function toBase64WebSafe(data) {
        return encode(data)
            .replace(/\+/g, '-')
            .replace(/\//g, '_')
            .replace(/=+$/, '')
    }
}

class HookMIMEMessage extends MIMEMessage {
    constructor(envctx) {
        super(envctx)
    }
}

export function createMimeMessage(envctx) {
    return new HookMIMEMessage(envctx)
}
```

**Comment by muratgozel** [comment]
Alright, I will make this on next release. You can also contribute if you want. Only point I care is that I want lib to stay dependency-free so if there is a way to implement this without importing any dependency I would prefer that. Otherwise that's okay. Thanks for bringing this up.

**Comment by toteto** [comment]
@muratgozel since you prefer 0 dependency package, maybe would be acceptable that the base64 encoder to be injected in the `createMimeMessage` by the consumer? It will be our responsibility to make sure the base64 encoding is good.

I would prefer this option since I will be sure that the base64 encoding is optimal and there is no performance, memory and bundle size hit.

Are you willing to take PR for this?

**Comment by rugbbyli** [comment]
@muratgozel Glad to hear that. I have thought push a MR for that, but I'm not familiar with node package's distribution flow. So it may be better to be done by some professional guys.

@toteto I think the `envctx` is just the thing you wanted.

**Comment by toteto** [comment]
@rugbbyli Yes, but it is not exposed for me to inject custom `envctx`.

**Comment by muratgozel** [comment]
@toteto @rugbbyli hey guys, i'm revisiting this issue and what came to me is that wouldn't it make sense if we just do `window.btoa = ...` somewhere in our app codebase, on unsupported browsers? its polyfilling basically and we can do that without the need for manipulating `envctx` or mimetext.

@toteto thanks for the PR btw. i just trying to keep the codebase simple and dependency free. will review it after we came into conclusion on this.

what do you all think?

**Comment by rugbbyli** [comment]
Hi @muratgozel , personally, I would avoid to modify the system interface, thought it could be unstable and difficult to maintain and may cause some unexpected behaviors.

Also, with some grammar (like the PR using), the interface could stay simple mostly. most people would just using it like before without any changes, and the build of custom `envctx` by user would be minimize (only care about what they want to override). 

So i think it's acceptable.

**Comment by muratgozel** [comment]
Closing this issue as of the later versions of this library started using an external base64 encoding library in its browser bundle.
