### ISSUE TITLE
Add more options for recipients: cc, bcc, message-ID

### ISSUE THREAD

**Issue by Larox** [muratgozel/MIMEText#2]
Hi, @muratgozel I've started using MIMEText and I'm enjoying how simple is to create email messages using it.

I have a question, is there a plan to include `cc` and `bcc` recipient options?  If so, when is this planned to be released? 

Also, is there any chance to manually set `message-ID` for reply option? 

I'll be glad to open a PR for adding this requirements if you like the idea. 

Thanks in advance

**Comment by muratgozel** [comment]
Happy to see someone using this library and yes a PR for those improvements would be appreciated.

Note to myself: I should add tests to this library as soon as possible.

**Comment by muratgozel** [comment]
bcc, cc support and many other features are now available as of version 1.0.0
