### ISSUE TITLE
v2.0.8: Missing `dist` folder when running `npm install`

### ISSUE THREAD

**Issue by henriquesalvaro** [muratgozel/MIMEText#23]
We just ran into issues when deploying our application:
`Error: Cannot find module '/app/node_modules/mimetext/dist/node/cjs/index.js'`
Checking it locally it looks like the `dist` folder is not being included when installing `v2.0.8` of the lib.
`npm install mimetext@2.0.7`
![image](https://user-images.githubusercontent.com/8291177/187288687-42e7bd30-80b4-4933-9224-f77367d8b108.png)
`npm install mimetext@2.0.8`
![image](https://user-images.githubusercontent.com/8291177/187288756-779ef910-0b6f-4525-bf75-337e99cb6aa9.png)
We locked the version on 2.0.7 and all is well for us.
Just a heads up! :)

**Comment by muratgozel** [comment]
Hey! I'm very sorry, forgot to run the build command on release. Fixed it! ✌️ Please do `npm update mimetext`.
