### ISSUE TITLE
error: Cannot read properties of undefined (reading 'byteLength')

### ISSUE THREAD

**Issue by atulmala** [muratgozel/MIMEText#25]
below is the code:

import { Injectable } from '@nestjs/common';
import { SES, SESClient } from '@aws-sdk/client-ses';
import { SendEmailCommand } from "@aws-sdk/client-ses";

const {fromIni} = require("@aws-sdk/credential-providers");

const fs = require('fs');
const request = require('request');
const nodemailer = require("nodemailer");
const {createMimeMessage} = require('mimetext');

@Injectable()
export class EmailAdapter {
  constructor() {
  }

  async sendEmail (name: string, recipients: string, subject: string, content: string) {
    const REGION = "us-east-1";
    const ses = new SES({ 
      region: REGION,
      credentials: {
        accessKeyId: 'XXXX',
        secretAccessKey: 'XXXX',
      }
    });
    
    // console.log ('ses: ', ses.config.credentials.toString());
    // const sesClient = new SESClient({ region: REGION });
    // console.log ('sesClient: ', sesClient);
    const message = createMimeMessage();

    message.setSender({name: 'GuruQ Support Team', addr: 'guruqwebdevelop@gmail.com'});
    console.log ('message.getSender(): ', message.getSender());
    message.setTo({name: 'Foo Bar', addr: 'guruq.mobile@gmail.com'});
    console.log ('message.getTo(): ', message.getRecipients());
    message.setSubject(subject)
    console.log ('message.getSubject(): ', message.getSubject());
    message.setAttachment('invoice.pdf', 'application/pdf', message.toBase64(fs.readFileSync('/Users/atulmala/guruq/media/media/7/2022/9/invoice_Q22OR14673.pdf')));
    console.log ('message.getAttachment(): ', message.getAttachments());
    const encoded = message.toBase64('This is <strong>html</strong>.')
    const headers = {'Content-Transfer-Encoding': 'base64'}
    message.setMessage('text/html', encoded, headers);
    message.setMessage("text/plain", encoded, headers);
    console.log ('message.getMessage(): ', message.getMessageByType('text/plain'));

    const params = {
      Destinations: message.getRecipients({type: 'to'}).map(mailbox => mailbox.addr),
      RawMessage: {
        Data: message.asRaw() // aws-sdk does the base64 encoding
      },
      Source: message.getSender().addr
    }

    console.log ('params.Destinaations = ', params.Destinations);

    ses.send
    
    ses.sendRawEmail(params, function(err, result) {
      if (err)  {
        console.log ('error:', err.message)
      }
      if (result) {
        console.log ('result: ', result.MessageId);
      }
      // err or result.MessageId
    })

    const command = new SendEmailCommand({
      Destination: {
        /* required */
        CcAddresses: [
          /* more items */
        ],
        ToAddresses: [
          recipients,
          /* more To-email addresses */
        ],
      },
      Message: {
        /* required */
        Body: {
          /* required */
          Html: {
            Charset: "UTF-8",
            Data: content,
          },
          Text: {
            Charset: "UTF-8",
            Data: "TEXT_FORMAT_BODY",
          },
        },
        Subject: {
          Charset: "UTF-8",
          Data: subject,
        },
      },
      
      Source: "guruqwebdevelop@gmail.com",
      ReplyToAddresses: [
        /* more items */
      ],
    });

    // try {
    //   return await sesClient.send(command);
    // } catch (e) {
    //   console.error("Failed to send email.");
    //   console.log(e);
    //   return e;
    // }
  }

**Comment by hokyunrhee** [comment]
[#3992](https://github.com/aws/aws-sdk-js-v3/issues/3992) It works for me.

**Comment by muratgozel** [comment]
hi @atulmala still having this issue?

**Comment by dwin-scott-kao** [comment]
> [#3992](https://github.com/aws/aws-sdk-js-v3/issues/3992) It works for me.
Thank you.
This works for me, too
