### ISSUE TITLE
Expose MIMEHeader and MIMEMessageContent

### ISSUE THREAD

**Issue by ruben-treams** [muratgozel/MIMEText#26]
Hi,

I'm trying to send ical invites through e-mail, but I'm not able to add custom messages because the classes aren't exported / exposed. Could you add this?

**Comment by muratgozel** [comment]
Hi @ruben-treams sorry for late reply, could you share more details about this please? including your code if possible because, ideally, there is really no need to access those classes.

**Comment by muratgozel** [comment]
they all exposed as of version v3.0.19, closing this issue.
