### ISSUE TITLE
Message chunking breaks images and links

### ISSUE THREAD

**Issue by askkaz** [muratgozel/MIMEText#28]
The release of v2.1.0 included chunking messages. One issue with this is that it seems to be adding newlines in the middle of content where there are side effects. For example, when a chunk happens in the middle of a link like `https://place-puppy.com/public-images/index-page/image1/210x280-lg.jpg`, it will show up in the original message like:
```
(.... some long text) <img src=3D"https://place-puppy.com/public-images/index-pa
ge/image1/210x280-lg.jpg"/>
```
When this is loaded into the email client (gmail in this case), it is interpreted as:
```
(.... some long text) <img src="https://place-puppy.com/public-images/index-pa%0Dge/image1/210x280-lg.jpg"/>
```
Which does not load.

**Comment by muratgozel** [comment]
hey @askkaz @thomaskvnze sorry for the inconvenience, reverted the feature. update to v2.1.1 please.

**Comment by thomaskvnze** [comment]
No problem. Thanks for the quick fix! Guess it will also help others!

**Comment by VRMink** [comment]
> hey @askkaz @thomaskvnze sorry for the inconvenience, reverted the feature. update to v2.1.1 please.

Hey @muratgozel. 
Did you do further on #21 and this #28? I have the problem same original problem, implemented a manual fix, then got the side effect that @thomaskvnze highlighted and now I am stuck with no solution.

Do you know what people have done for a solution?
