### ISSUE TITLE
Headers Order

### ISSUE THREAD

**Issue by andrenacu** [muratgozel/MIMEText#37]
Hi Great work. I need to clone emails to forward for content investigation. Is there a way to replicate the order of an email headers exactly. When I parse an email and set from, to, and subject then additional headers it will order the headers as date, from, to, message-id, subject, mime-version then addition headers. I understand this library is meant to create and send emails, I was just wondering if there is a way to add in an object of headers as intended order whereas there may be header keys like recieved, authentications-results, received-sfp, dkim-signature, x-google-dkim-signature etc ordered before date, from and to. Thank you.

**Comment by muratgozel** [comment]
Hi @andrenacu Headers isn't guaranteed to have an order. I'm currently updating the library and will have a look if there is something I can do to achieve this without breaking specification and api.

**Comment by andrenacu** [comment]
Thank you @muratgozel for your reply. I will be looking forward to the updates.

**Comment by arndesk** [comment]
Is there any update about this?
