### ISSUE TITLE
Could not find a declaration file for module 'MIMEText'.

### ISSUE THREAD

**Issue by andreid42tech** [muratgozel/MIMEText#38]
Hey! How can we fix this issue in the package?

**Comment by muratgozel** [comment]
hi @andreid42tech that was probably because of the naming issue in the type declaration file, just fixed it. could you update and confirm that the issue resolved?

**Comment by andreid42tech** [comment]
> hi @andreid42tech that was probably because of the naming issue in the type declaration file, just fixed it. could you update and confirm that the issue resolved?

Hey, it didn't help.

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/119295676/230896704-600f1f98-4f56-4e75-86fe-dd994b7fd0c5.png">

**Comment by muratgozel** [comment]
@andreid42tech could you share your setup so I can simulate your environment and test it? Share repository if possible, or your ide, package.json and other config files.

**Comment by muratgozel** [comment]
type declaration is scoped with `declare module 'mimetext'` so ideally, there shouldn't be any conflict but I'll check this out and maybe will just publish dist and types as you have suggested. I need a few days for this, thanks for bringing this up.

**Comment by andreid42tech** [comment]
> @andreid42tech type declaration is scoped with `declare module 'mimetext'` so ideally, there shouldn't be any conflict but I'll check this out and maybe will just publish dist and types as you have suggested. I need a few days for this, thanks for bringing this up.
> 
> besides, i would recommend to check if there is any package you have installed called @types/mimetext. remove it if exists.

Thanks!

**Comment by muratgozel** [comment]
hi @andreid42tech update to the latest version please, is the problem still continue?

**Comment by andreid42tech** [comment]
> 

Hey @muratgozel, yes, I think it is due to this library being sourced fully and not bundled/compiled, could that be true?

<img width="1877" alt="image" src="https://github.com/muratgozel/MIMEText/assets/119295676/62b1e83b-66c4-4ed5-ae87-75827b70c4f2">

**Comment by ColinCee** [comment]
I'm getting the same error when switching typescript config `moduleResolution` to `node16`

This is most likely related to the mess that is es modules, either this repo needs to support esm or just stick to using commonjs modules

**Comment by zhahaoyu** [comment]
I am facing the same issue.

Here is the same tsconfig. 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by zhahaoyu** [comment]
<img width="946" alt="Screen Shot 2023-09-27 at 10 49 17 PM" src="https://github.com/muratgozel/MIMEText/assets/13268361/67e715e5-7844-48cc-822e-73e659a5e7dc">

**Comment by iainmerrick** [comment]
Just sent a PR which fixes this for me. It's a bit clunky and doesn't handle CJS but should at least get things working for ES users.

**Comment by muratgozel** [comment]
@andreid42tech i have updated type generations, give it another go if possible, please, it should all be fixed now.

**Comment by muratgozel** [comment]
closing this issue as all the type recognition issues has been resolved.
