### ISSUE TITLE
Corrupted Image/PDF attachments

### ISSUE THREAD

**Issue by Quesj** [muratgozel/MIMEText#39]
Hi, 

I'm having issues viewing attachments I've added to my email. I load the files locally from my pc (Mac) and after creating the message I write it back to my system to view it in Microsoft Outlook. I however get corrupted files/ no pdf/jpg file errors... Sending a text file as attachment works (testRaw). "dataRaw" gives the corrupted error messages

### Code: 
```js
import { createMimeMessage } from "mimetext";
import fs from "fs";

export const dummyMime = () => {
  const msg = createMimeMessage();
  msg.setSender({ name: "Dummy", addr: "DummyTummy@gmail.com" });
  msg.setRecipient("TummyDummy@gmail.com");
  msg.setSubject("A dummy email to test with");
  msg.addMessage({
    contentType: "text/plain",
    data: `Hello, my name is Dummy and this is a dummy email to test the email parsed with - I enjoy typescript!`,
  });

  const dataRaw = fs.readFileSync('dummy2.jpg', {encoding: 'base64'});
  const testRaw = Buffer.from("this is a text!").toString('base64');

  msg.addAttachment({
    filename: "dummy2.jpg",
    contentType: "image/jpg",
    data: `${dataRaw}`,
  });
  
  fs.writeFile("dummyEmail.eml", msg.asRaw(), (err) => {
    if (!err) {
      console.log("email succesfully generated");
      console.log(msg.asRaw());
    }
  });

  return msg.asRaw();
};

dummyMime();
```

![dummy2](https://user-images.githubusercontent.com/43757380/233292995-71f6fdf0-2fc1-4a9c-b306-38f8b20eb12d.jpg)

**Comment by Quesj** [comment]
Hi, thank you for checking - I do not have mail setup, perhaps it’s MS Outlook that’s messing the file up. Could you try and reproduce my error with MS Outlook?

**Comment by Quesj** [comment]
Solved (partially)!

Issue was caused by conflicting package installs by npm/yarn. Delete node_modules folder and install again using either yarn/npm.

**Comment by muratgozel** [comment]
@Quesj why partially?

**Comment by Quesj** [comment]
> 

Because I am still unable to open attachment files in MS Outlook - I need to be able to open them there... See issue #40
