### ISSUE TITLE
Move types to devDependencies

### ISSUE THREAD

**Issue by shyim** [muratgozel/MIMEText#60]
<img width="755" alt="image" src="https://github.com/muratgozel/MIMEText/assets/6224096/c104feac-1449-4abe-8592-04b6c5fc11a8">

I think only `js-base64` and `mime-types` should be dependencies. Everything else are dev dependencies I think 🤔

**Comment by muratgozel** [comment]
they have been moved 🙂 thank you. update the lib to the latest version please. closing this issue but open again if you face any more problems.
