### ISSUE TITLE
Mailbox function signature changes in patch release?

### ISSUE THREAD

**Issue by PodStuart** [muratgozel/MIMEText#65]
I can see from the issue history there have been some typing issues beyond 3.0.16. I was seeing issues similar to others from 3.0.17 to 3.0.20 but these have been resolved in 3.0.21 but replaced by another problem.

Mailbox.getRecipients() used to return `Mailbox | Mailbox[] | undefined`.

It now returns `string | Mailbox | undefined`.

Mailbox.getSender() used to return `Mailbox | undefined`

It now returns `string | Mailbox | undefined`.

These changes are causing TypeScript errors in our builds.

Node version 20.11.0.
Nx version 18.0.4.
Typescript version 5.3.3.

Happy to provide any further information required.

**Comment by muratgozel** [comment]
@PodStuart hi again, i did corrections on few definitions including `getRecipients` and `getSender`:
- `getRecipients` now returns `Mailbox | Mailbox[] | undefined` as expected
- `getSender` now returns `Mailbox | undefined`

**Comment by PodStuart** [comment]
Thanks for sorting that.
