### ISSUE TITLE
Upgrading from mimetext version 3.0.16 to 3.0.21 throws cannot use import statement outside a module

### ISSUE THREAD

**Issue by jeremy-brooks** [muratgozel/MIMEText#68]
Problem:

Upgrading from mimetext version 3.0.16 to 3.0.21 causes a test failure when trying to use CommonJS require:
```
const { createMimeMessage } = require('mimetext');
```

Throwing the following error:
```
Details:

    /#################/node_modules/mimetext/build/MIMEMessage.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { MIMETextError } 
from './MIMETextError.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | const { createMimeMessage } = require('mimetext');
```

Currently pinning to 3.0.16 to get build working again.

**Comment by ir-fuel** [comment]
and this is why I only use exact version numbers in my package.json files. You never know when things break that are supposed to be "backwards compatible".

**Comment by jeremy-brooks** [comment]
> and this is why I only use exact version numbers in my package.json files. You never know when things break that are supposed to be "backwards compatible".

We control our versions via good use of the `package-lock.json` file and only do updates via automated PR's using dependabot. We do not allow versions to shift without us deciding to approve and merge a PR, so it's a nice way to have pipelines run against package updates in isolation and quickly see if there is a breaking change via automated testing. Of course some things get through the gaps where testing was not covering, but it works well most of the time.

**Comment by muratgozel** [comment]
closing this issue as it should be resolved in the latest version.
